import {
  FiShield,
  FiFileText,
  FiCheckCircle,
  FiAlertTriangle,
  FiActivity,
  FiLock,
  FiEye,
  FiGlobe,
  FiSmartphone,
  FiCloud,
} from 'react-icons/fi'

export const services = [
  {
    id: 'vapt',
    title: 'VAPT (Vulnerability Assessment & Penetration Testing)',
    slug: 'vapt',
    icon: FiShield,
    badge: 'Popular',
    shortDescription: 'Comprehensive security testing for web, network, mobile, and cloud infrastructure to identify and remediate vulnerabilities.',
    overview: 'Our VAPT services combine automated vulnerability scanning with manual penetration testing to provide comprehensive security assessments. We identify security weaknesses before attackers do and provide detailed remediation guidance.',
    whyMatters: [
      'Proactive identification of security vulnerabilities',
      'Compliance with security standards and regulations',
      'Protection against cyber attacks and data breaches',
      'Validation of security controls and defenses',
      'Risk mitigation and security posture improvement',
    ],
    deliverables: [
      'Detailed vulnerability assessment report',
      'Executive summary with risk ratings',
      'Proof-of-concept exploits (when applicable)',
      'Remediation recommendations with priorities',
      'Re-testing after fixes (optional)',
      'Security awareness presentation',
    ],
    methodology: [
      'Planning and scoping',
      'Information gathering and reconnaissance',
      'Vulnerability scanning and analysis',
      'Manual penetration testing',
      'Exploitation and privilege escalation',
      'Reporting and remediation support',
    ],
    tools: ['Burp Suite Pro', 'Nmap', 'Metasploit', 'OWASP ZAP', 'Nessus', 'SQLMap', 'Custom Scripts'],
    timeline: '2-6 weeks depending on scope',
    whoShouldUse: [
      'Organizations handling sensitive data',
      'E-commerce and fintech companies',
      'Healthcare providers',
      'Government agencies',
      'Companies seeking compliance certification',
      'Startups launching new products',
    ],
    modules: [
      {
        name: 'Web Application VAPT',
        description: 'Testing for OWASP Top 10, business logic flaws, and API security',
      },
      {
        name: 'Network VAPT',
        description: 'Assessment of network infrastructure, firewalls, and segmentation',
      },
      {
        name: 'Mobile App VAPT',
        description: 'iOS and Android application security testing',
      },
      {
        name: 'Cloud VAPT',
        description: 'AWS, Azure, and GCP infrastructure security assessment',
      },
    ],
    faqs: [
      {
        question: 'What is the difference between VA and PT?',
        answer: 'Vulnerability Assessment (VA) is an automated scan to identify known vulnerabilities, while Penetration Testing (PT) involves manual testing to exploit vulnerabilities and assess real-world impact.',
      },
      {
        question: 'Will testing disrupt our systems?',
        answer: 'We conduct testing in a controlled manner to minimize disruption. We can schedule tests during off-peak hours and coordinate with your team.',
      },
      {
        question: 'How often should we conduct VAPT?',
        answer: 'We recommend quarterly assessments for critical systems and at least annually for all systems. Additional testing should be done after major changes.',
      },
    ],
  },
  {
    id: 'iso-27001',
    title: 'ISO 27001 Implementation',
    slug: 'iso-27001',
    icon: FiFileText,
    shortDescription: 'Complete ISO 27001 certification support from gap analysis to audit preparation and ongoing compliance.',
    overview: 'We provide end-to-end ISO 27001 implementation services, helping organizations establish, implement, and certify their Information Security Management System (ISMS).',
    whyMatters: [
      'Demonstrates commitment to information security',
      'Required by many clients and partners',
      'Reduces security risks systematically',
      'Competitive advantage in procurement',
      'International recognition and credibility',
    ],
    deliverables: [
      'Gap analysis report',
      'ISMS documentation (policies, procedures, records)',
      'Risk assessment and treatment plan',
      'Statement of Applicability (SoA)',
      'Internal audit reports',
      'Management review documentation',
      'Certification audit support',
    ],
    methodology: [
      'Initial gap analysis',
      'Scope definition and planning',
      'Risk assessment',
      'Policy and procedure development',
      'Implementation support',
      'Internal audit',
      'Management review',
      'Certification audit preparation',
    ],
    tools: ['Risk assessment tools', 'Document management systems', 'Compliance tracking platforms'],
    timeline: '3-6 months for full implementation',
    whoShouldUse: [
      'Organizations handling sensitive data',
      'IT service providers',
      'Financial institutions',
      'Healthcare organizations',
      'Government contractors',
      'Companies seeking international clients',
    ],
    faqs: [
      {
        question: 'How long does ISO 27001 certification take?',
        answer: 'Typically 3-6 months for implementation plus 2-4 weeks for the certification audit process.',
      },
      {
        question: 'What are the costs involved?',
        answer: 'Costs include our consulting fees, certification body audit fees, and any required tools or training. We provide detailed cost estimates during initial consultation.',
      },
    ],
  },
  {
    id: 'iso-9001',
    title: 'ISO 9001 Implementation',
    slug: 'iso-9001',
    icon: FiCheckCircle,
    shortDescription: 'Quality management system implementation for operational excellence and continuous improvement.',
    overview: 'ISO 9001 quality management system implementation to help organizations improve processes, enhance customer satisfaction, and achieve operational excellence.',
    whyMatters: [
      'Improves operational efficiency',
      'Enhances customer satisfaction',
      'Streamlines processes',
      'Competitive market advantage',
      'Facilitates continuous improvement',
    ],
    deliverables: [
      'Gap analysis report',
      'Quality manual',
      'Process documentation',
      'Quality objectives and KPIs',
      'Internal audit program',
      'Corrective action procedures',
      'Certification support',
    ],
    methodology: [
      'Gap analysis',
      'Process mapping',
      'Documentation development',
      'Implementation support',
      'Internal audits',
      'Management review',
      'Certification preparation',
    ],
    tools: ['Process mapping tools', 'Quality management software', 'Audit management platforms'],
    timeline: '3-5 months',
    whoShouldUse: [
      'Manufacturing companies',
      'Service providers',
      'Organizations seeking quality improvement',
      'Companies pursuing procurement opportunities',
    ],
    faqs: [
      {
        question: 'Can we implement ISO 9001 and ISO 27001 together?',
        answer: 'Yes, we offer integrated management system implementation which is more efficient and cost-effective.',
      },
    ],
  },
  {
    id: 'pci-dss',
    title: 'PCI DSS Compliance',
    slug: 'pci-dss',
    icon: FiLock,
    shortDescription: 'Payment Card Industry Data Security Standard compliance for organizations handling credit card data.',
    overview: 'Complete PCI DSS compliance support including gap analysis, remediation, and validation for organizations processing, storing, or transmitting credit card information.',
    whyMatters: [
      'Legal requirement for handling card data',
      'Reduces risk of data breaches',
      'Protects customer payment information',
      'Avoids hefty fines and penalties',
      'Maintains payment processing privileges',
    ],
    deliverables: [
      'PCI DSS gap analysis',
      'Network segmentation recommendations',
      'Policy and procedure templates',
      'Security configuration guidelines',
      'SAQ (Self-Assessment Questionnaire) completion',
      'AOC (Attestation of Compliance)',
      'Quarterly vulnerability scans',
    ],
    methodology: [
      'Scoping and network segmentation',
      'Gap analysis against 12 requirements',
      'Remediation planning',
      'Implementation support',
      'Security assessment',
      'Documentation and reporting',
      'QSA audit support',
    ],
    tools: ['Vulnerability scanners', 'Log management', 'File integrity monitoring', 'IDS/IPS'],
    timeline: '2-4 months',
    whoShouldUse: [
      'E-commerce platforms',
      'Payment processors',
      'Retail businesses',
      'Hospitality industry',
      'Any merchant accepting credit cards',
    ],
    faqs: [
      {
        question: 'Do I need PCI DSS compliance?',
        answer: 'If you store, process, or transmit credit card data, PCI DSS compliance is mandatory regardless of business size.',
      },
      {
        question: 'What level of PCI DSS applies to us?',
        answer: 'This depends on your annual transaction volume. We help determine your level during initial assessment.',
      },
    ],
  },
  {
    id: 'soc-2',
    title: 'SOC 2 Readiness',
    slug: 'soc-2',
    icon: FiEye,
    shortDescription: 'SOC 2 compliance preparation covering security, availability, confidentiality, and privacy controls.',
    overview: 'We help technology and cloud service providers prepare for SOC 2 audits by implementing required controls and processes based on AICPA Trust Services Criteria.',
    whyMatters: [
      'Required by enterprise customers',
      'Demonstrates trustworthiness',
      'Competitive advantage in SaaS market',
      'Systematic risk management',
      'Enhanced customer confidence',
    ],
    deliverables: [
      'Readiness assessment',
      'Gap analysis report',
      'Control documentation',
      'Policy and procedure development',
      'Evidence collection framework',
      'Mock audit execution',
      'Audit readiness report',
    ],
    methodology: [
      'Scope definition (Type I or Type II)',
      'Trust Services Criteria mapping',
      'Control identification and gap analysis',
      'Control implementation',
      'Evidence gathering process setup',
      'Readiness assessment',
      'Audit support',
    ],
    tools: ['GRC platforms', 'Evidence collection tools', 'Monitoring systems'],
    timeline: '3-6 months for readiness',
    whoShouldUse: [
      'SaaS companies',
      'Cloud service providers',
      'Technology startups',
      'Data hosting providers',
      'Companies serving enterprise clients',
    ],
    faqs: [
      {
        question: 'What is the difference between SOC 2 Type I and Type II?',
        answer: 'Type I evaluates controls at a point in time, while Type II assesses control effectiveness over a period (typically 3-12 months).',
      },
    ],
  },
  {
    id: 'risk-assessment',
    title: 'Risk Assessment & Governance',
    slug: 'risk-assessment',
    icon: FiAlertTriangle,
    shortDescription: 'Comprehensive cybersecurity risk assessment and governance framework development.',
    overview: 'Identify, analyze, and prioritize cybersecurity risks with actionable remediation plans aligned with business objectives and regulatory requirements.',
    whyMatters: [
      'Informed security investment decisions',
      'Regulatory compliance',
      'Board-level risk visibility',
      'Resource prioritization',
      'Insurance and liability management',
    ],
    deliverables: [
      'Risk assessment report',
      'Risk register',
      'Risk treatment plan',
      'Governance framework',
      'Policy templates',
      'Risk dashboard',
      'Executive presentations',
    ],
    methodology: [
      'Asset identification',
      'Threat modeling',
      'Vulnerability assessment',
      'Risk analysis and scoring',
      'Risk treatment recommendations',
      'Governance framework design',
      'Ongoing monitoring setup',
    ],
    tools: ['Risk assessment frameworks', 'Threat intelligence', 'Asset management tools'],
    timeline: '4-8 weeks',
    whoShouldUse: [
      'Organizations without formal risk programs',
      'Companies seeking compliance',
      'Enterprises with complex environments',
      'Organizations undergoing digital transformation',
    ],
    faqs: [
      {
        question: 'How often should risk assessments be conducted?',
        answer: 'Annually at minimum, with updates after major changes or incidents.',
      },
    ],
  },
  {
    id: 'it-audit',
    title: 'IT / IS Audit',
    slug: 'it-audit',
    icon: FiActivity,
    shortDescription: 'Independent IT and information security audits to verify controls and compliance.',
    overview: 'Independent assessment of IT controls, security practices, and compliance with standards, regulations, and internal policies.',
    whyMatters: [
      'Independent validation of controls',
      'Regulatory compliance',
      'Risk identification',
      'Improvement recommendations',
      'Stakeholder assurance',
    ],
    deliverables: [
      'Audit report with findings',
      'Risk ratings and priorities',
      'Management letter',
      'Remediation recommendations',
      'Follow-up audit (optional)',
    ],
    methodology: [
      'Audit planning and scoping',
      'Control documentation review',
      'Testing and evidence gathering',
      'Interviews and observations',
      'Gap analysis',
      'Reporting',
    ],
    tools: ['Audit management software', 'Testing tools', 'Documentation platforms'],
    timeline: '2-6 weeks',
    whoShouldUse: [
      'Organizations with compliance requirements',
      'Companies undergoing M&A',
      'Board-mandated audit requirements',
      'Third-party assurance needs',
    ],
    faqs: [],
  },
  {
    id: 'incident-response',
    title: 'Incident Response Support',
    slug: 'incident-response',
    icon: FiAlertTriangle,
    shortDescription: '24/7 incident response services for security breaches and cyber attacks.',
    overview: 'Rapid incident response support to contain, investigate, and recover from security incidents with minimal business impact.',
    whyMatters: [
      'Minimize breach impact',
      'Faster recovery time',
      'Expert investigation',
      'Evidence preservation',
      'Lessons learned implementation',
    ],
    deliverables: [
      'Incident response plan',
      'Retainer services (optional)',
      'Forensic investigation reports',
      'Containment and eradication support',
      'Recovery assistance',
      'Post-incident review',
    ],
    methodology: [
      'Preparation',
      'Detection and analysis',
      'Containment',
      'Eradication',
      'Recovery',
      'Post-incident activities',
    ],
    tools: ['Forensic tools', 'SIEM', 'EDR', 'Memory analysis', 'Network analysis'],
    timeline: 'Immediate response / Ongoing retainer',
    whoShouldUse: [
      'All organizations',
      'High-risk industries',
      'Compliance-driven organizations',
      'Companies without internal SOC',
    ],
    faqs: [
      {
        question: 'Do you offer 24/7 support?',
        answer: 'Yes, our incident response team is available 24/7/365 for retainer clients.',
      },
    ],
  },
  {
    id: 'secure-architecture',
    title: 'Secure Architecture Review',
    slug: 'secure-architecture',
    icon: FiGlobe,
    shortDescription: 'Security architecture review and design for applications and infrastructure.',
    overview: 'Expert review of system architecture, design patterns, and security controls to identify weaknesses and provide secure design recommendations.',
    whyMatters: [
      'Security by design',
      'Cost-effective early intervention',
      'Compliance alignment',
      'Scalability and security balance',
      'Technical debt reduction',
    ],
    deliverables: [
      'Architecture review report',
      'Threat model',
      'Security design recommendations',
      'Reference architecture',
      'Implementation roadmap',
    ],
    methodology: [
      'Architecture documentation review',
      'Threat modeling',
      'Security control assessment',
      'Best practice comparison',
      'Recommendation development',
    ],
    tools: ['Threat modeling tools', 'Architecture diagram tools', 'Security frameworks'],
    timeline: '2-4 weeks',
    whoShouldUse: [
      'Development teams',
      'Cloud migration projects',
      'New product development',
      'Legacy system modernization',
    ],
    faqs: [],
  },
  {
    id: 'consulting',
    title: 'Cybersecurity Consulting',
    slug: 'consulting',
    icon: FiShield,
    shortDescription: 'Strategic cybersecurity consulting for security program development and improvement.',
    overview: 'Strategic guidance on all aspects of cybersecurity including program development, vendor selection, security strategy, and custom projects.',
    whyMatters: [
      'Expert strategic guidance',
      'Vendor-neutral advice',
      'Cost optimization',
      'Tailored solutions',
      'Knowledge transfer',
    ],
    deliverables: [
      'Custom deliverables based on engagement',
      'Strategic recommendations',
      'Implementation roadmaps',
      'Vendor evaluation reports',
      'Training materials',
    ],
    methodology: [
      'Requirements gathering',
      'Current state assessment',
      'Best practice research',
      'Recommendation development',
      'Implementation support',
    ],
    tools: ['Varies by project'],
    timeline: 'Varies by project',
    whoShouldUse: [
      'Organizations building security programs',
      'Companies seeking expert advice',
      'Custom security projects',
      'Vendor selection support',
    ],
    faqs: [
      {
        question: 'What types of consulting do you offer?',
        answer: 'We offer strategy development, program assessment, vendor selection, security awareness, and custom consulting projects.',
      },
    ],
  },
]
